# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streetartpost',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='streetartpost',
            name='id',
        ),
        migrations.RemoveField(
            model_name='streetartpostvote',
            name='id',
        ),
        migrations.AddField(
            model_name='streetartpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streetartpost',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='streetartpostvote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streetartpostvote',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
