# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0002_auto_20170607_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetartpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
