# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0003_auto_20170607_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetartpost',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='streetartpost',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
